### PR TITLE
Deprecating in favor of Playdoh

### PR DESCRIPTION
**Pull request by HelloGrayson**
cc @blampe @sectioneight

### CODE REVIEW

**Comment by HelloGrayson** [comment]
I'm going to close all PR's and tickets after this.

**Comment by ascandella** [comment]
Why not just archive the repo? Or are there things in the repo you want to leave?

**Comment by HelloGrayson** [comment]
According to @sh1mmer this is open source and is used by another team :(

**Comment by sh1mmer** [comment]
First thing, this is an open source project so we should figure out what to do if we retire those internally. Secondly, I believe teams at Uber are still using it. 

cc @lxe

**Comment by HelloGrayson** [comment]
@sectioneight the problem is that people are still using this to scaffold new projects, when they shouldn't be. We'll work with the right people to figure out what to do.

**Comment by ascandella** [comment]
sigh

**Comment by Raynos** [comment]
- we can retire this project.
- lets leave the code here because OSS
- lets update the README to clearly mark it as deprecated

Any uber internal communication around best practices will have to be solved differently.

**Pull request closed without merging**
